### ISSUE TITLE
owl:sameAs (bug)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#345] opened 2023-04-03 12:56 UTC
Hello @fkraeutli and @olyanicolaeva ,

We have a big bug with external ressources. All the time we want to modify a entity, a warning come with external ressource.

Ex: http://data.performing-arts.ch/a/9d1d8fc8-2c9a-46c8-bfc7-6ac097003725

![image](https://user-images.githubusercontent.com/8588224/229515677-1e46146b-ab2f-4073-bff4-a2f47351b6ff.png)

Thanks for your quick help :-)

**Comment by olyanicolaeva** [comment] 2023-04-03 17:07
hi @b2d3c I don't seem to be able to reproduce it on the production server:
![Screenshot 2023-04-03 at 19 04 37](https://user-images.githubusercontent.com/86773892/229578880-cbf12b71-a740-4dbc-97a2-bd024381561e.png)

Would you have a moment to have a look in person?

**Comment by b2d3c** [comment] 2023-04-04 06:25
Hello @olyanicolaeva : you have to save (with or without modification) and then the bug come.

**Comment by olyanicolaeva** [comment] 2023-04-04 08:10
the bug might have to do with commit 83d04c7 , where the datatype has been changed from anyURI to string. 

@fkraeutli would that be an option to reassign the datatype to all existing resources in the blazegraph, so that they are all strings? Or is it possible to ignore type here?

**Comment by b2d3c** [comment] 2023-04-06 07:03
Hello @olyanicolaeva and @fkraeutli : have you time for this Issue today? Or could you give us a planning of resolution ? 
Thanks in advance

**Comment by olyanicolaeva** [comment] 2023-04-06 07:46
hi @b2d3c , Florian is off this week. We will be able to decide on the long-term solution next week. It is either that we will need to reassign the datatype to the existing URIs or the fix in this [commit](https://github.com/sapa/performing-arts-ch-templates/commit/83d04c7f4f4b57f1c4c089a69eb096e2741908b2) will have to be changed. The commit mentioned above allows non uri characters in the links.

**Closed** 2023-04-11 09:37 UTC
Labels: bug

**Comment by fkraeutli** [comment] 2023-04-11 09:40
Hi @b2d3c , I fixed the issue and due to the blocking status deployed to both dev and prod. Can you check if the behaviour is correct and let me know?

The issue was that, for input, we treat the URL as String so we avoid the issue where the checking of the form fails due to non-allowed characters in the URL. On saving, the URL is saved correctly as URI datatype (not as string) in the database. When selecting it for displaying in the form we have to cast it back to a string however. This was previously not implemented and therefore the form checking failed where the URLs were not changed
